allowBuilds:
  '@google/genai': true
  '@prisma/engines': true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  openclaw: true
  prisma: true
  protobufjs: true
  sharp: true
  tree-sitter-bash: true
